name: iOS Build
on: [push, pull_request]

concurrency:
  group: ci-${{github.actor}}-${{github.head_ref || github.run_number}}-${{github.ref}}-ios
  cancel-in-progress: true

jobs:
  ios:
    name: 🍎
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        platform:
          - iOS
          - tvOS
        lib-type:
          - static       
    env:
      HOST: macOS
      PLATFORM: ${{ matrix.platform }}
      LIB_TYPE: ${{ matrix.lib-type }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with: { fetch-depth: 0 }
      - name: Cache
        uses: actions/cache@v4
        with:
          path: |
            build
          key: |
            ${{ matrix.platform }}-${{ matrix.lib-type }}-${{ runner.os }}-${{ runner.arch }}     
      - name: Select Xcode
        run: sudo xcode-select -s /Applications/Xcode.app
      - name: CMake
        run: rake cmake
      - name: Build
        run: rake build
      - name: Install
        run: rake install
      - name: Scaffolding - new
        run: rake new
      - name: Scaffolding - build
        run: |
          cd ~/projects/UrhoApp
          rake
      - name: Scaffolding - cleanup
        run: rm -rf ~/{.urho3d,projects}
      - name: Package
        run: rake package
        if: github.event_name == 'push'
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.platform }}-${{ matrix.lib-type }}-all-rel
          path: build/ci/*.tar.gz
        if: github.event_name == 'push'
      - name: Clean
        run: |
            rm -rf {build/ci/lib,build/ci/bin/*.app}
