name: QA
on: [push, pull_request]

concurrency:
  group: ci-${{github.actor}}-${{github.head_ref || github.run_number}}-${{github.ref}}-qa
  cancel-in-progress: true

jobs:
  qa:
    name: 🔬 Quality Assurance
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: true
    env:
      HOST: linux
      PLATFORM: linux-clang
      BUILD_TYPE: dbg
      LIB_TYPE: shared
      ARCH: 64
      DBE_TAG: master
      URHO3D_DOCS: 1
      USE_CCACHE: 1
      LLVM_USE_SPLIT_DWARF: 1
      LLVM_ENABLE_ASSERTIONS: 1
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with: { fetch-depth: 0 }
      - name: Source checksum
        id: source_checksum
        run: rake source_checksum
      - name: Cache
        uses: actions/cache@v4
        with:
          path: |
            build/cache/.ccache
          key: |
            ${{ env.PLATFORM }}-${{ env.LIB_TYPE }}-${{ env.ARCH }}-${{ env.BUILD_TYPE }}-${{ env.DBE_TAG }}-${{ steps.source_checksum.outputs.hexdigest }}
          restore-keys: |
            ${{ env.PLATFORM }}-${{ env.LIB_TYPE }}-${{ env.ARCH }}-${{ env.BUILD_TYPE }}-${{ env.DBE_TAG }}
            ${{ env.PLATFORM }}-${{ env.LIB_TYPE }}-${{ env.ARCH }}-${{ env.BUILD_TYPE }}
      - name: DBE
        run: rake update_dot_files && script/dockerized.sh ${PLATFORM/-*} env
      - name: CMake
        run: script/dockerized.sh ${PLATFORM/-*} rake cmake
      - name: Build
        run: script/dockerized.sh ${PLATFORM/-*} rake build
      - name: Lint
        run: script/dockerized.sh ${PLATFORM/-*} rake lint
        if: false # Disable linting for now
      - name: Style
        run: script/dockerized.sh ${PLATFORM/-*} rake style
      - name: Documentation
        run: script/dockerized.sh ${PLATFORM/-*} rake doc

